Repository FlaxEngine/FlaxEngine, pull requests merged in 2020-12, with the labels that each got.

#8 Title bar High DPI fix.
  Source/Editor/GUI/MainMenu.cs
Labels: enhancement

#7 Fix compiler errors with Vulkan 1.2.x
  Source/Engine/GraphicsDevice/Vulkan/DescriptorSetVulkan.cpp
  Source/Engine/GraphicsDevice/Vulkan/DescriptorSetVulkan.h
  Source/Engine/GraphicsDevice/Vulkan/GPUPipelineStateVulkan.cpp
  Source/Engine/GraphicsDevice/Vulkan/GPUPipelineStateVulkan.h
  Source/Engine/GraphicsDevice/Vulkan/RenderToolsVulkan.cpp
Labels: enhancement

#29 Fix wrong engine path with RegisterEng. as Admin.
  RegisterEngineLocation.bat
Labels: enhancement

#28 Fix flashing tooltips
  Source/Engine/UI/GUI/Tooltip.cs
  Source/Engine/UI/GUI/WindowRootControl.cs
Labels: bug

#31 Fix link to Github issue.
  Source/Editor/Utilities/Constants.cs
Labels: enhancement

#24 Fix double extensions when user specifies one during asset creation
  Source/Editor/Windows/ContentWindow.cs
Labels: enhancement

#36 Fix speed change scrolling being wonky
  Source/Editor/Viewport/EditorViewport.cs
Labels: enhancement

#38 Better handle double file extensions on rename
  Source/Editor/Windows/ContentWindow.cs
Labels: enhancement

#43 Fix more dpi issues
  Source/Editor/GUI/ContextMenu/ContextMenuBase.cs
  Source/Editor/GUI/Docking/DockHintWindow.cs
Labels: enhancement

#45 Change maximum window size to 4096
  Source/Editor/GUI/Docking/FloatWindowDockPanel.cs
Labels: enhancement

#60 Fix inverted Y Gizmo Rotation
  Source/Editor/Gizmo/TransformGizmoBase.cs
Labels: enhancement

#72 Support for Visual Studio Code Insiders
  Source/Editor/Modules/SourceCodeEditing/InBuildSourceCodeEditor.cs
  Source/Editor/Scripting/CodeEditor.h
  Source/Editor/Scripting/CodeEditors/VisualStudioCodeEditor.cpp
  Source/Editor/Scripting/CodeEditors/VisualStudioCodeEditor.h
Labels: enhancement

#66 Resolve issue where Values.Type resulted in System.Type
  Source/Editor/CustomEditors/Editors/TypeEditor.cs
Labels: enhancement

#73 Fix typos
  Source/Editor/Cooker/GameCooker.cpp
  Source/Engine/Animations/Graph/AnimGraph.Custom.cpp
  Source/Engine/Animations/Graph/AnimGraph.h
  Source/Engine/Animations/InverseKinematics.h
  Source/Engine/Animations/SceneAnimations/SceneAnimation.cpp
  Source/Engine/Animations/SceneAnimations/SceneAnimation.h
  Source/Engine/Animations/SceneAnimations/SceneAnimationPlayer.h
  Source/Engine/Audio/Audio.cpp
  Source/Engine/Audio/AudioSettings.h
  Source/Engine/Audio/AudioSource.h
  Source/Engine/Content/Assets/VisualScript.h
  Source/Engine/Content/Cache/AssetsCache.cpp
  Source/Engine/Content/Factories/IAssetFactory.h
  Source/Engine/Content/Utilities/IESLoader.h
Labels: enhancement

#21 Fix renaming files to same name with different case
  Source/Editor/Modules/ContentDatabaseModule.cs
  Source/Engine/Content/Content.cpp
Labels: editor, enhancement

#32 Adding "Generate collision data" from Model context menu.
  Source/Editor/Content/Proxy/CollisionDataProxy.cs
  Source/Editor/Windows/ContentWindow.ContextMenu.cs
Labels: editor, enhancement

#74 Change ClientFrom/ToScreen to PointFrom/ToScreen
  Source/Editor/Content/Items/AssetItem.cs
  Source/Editor/Editor.cs
  Source/Editor/GUI/ContextMenu/ContextMenuBase.cs
  Source/Editor/GUI/Docking/DockPanel.cs
  Source/Editor/Modules/UIModule.cs
  Source/Engine/UI/GUI/Control.cs
  Source/Engine/UI/GUI/Tooltip.cs
  Source/Engine/UI/GUI/WindowRootControl.cs
Labels: bug

#77 Fix build scenes toolstrip button enabled state
  Source/Editor/Modules/UIModule.cs
Labels: editor, enhancement

#78 Prevent loading 'null' style
  Source/Editor/Options/OptionsModule.cs
Labels: bug, editor
