Repository FlaxEngine/FlaxEngine, pull requests merged in 2021-09, with the labels that each got.

#620 Add Render2D::DrawTexturedTriangles variations
  Source/Engine/Render2D/Render2D.cpp
  Source/Engine/Render2D/Render2D.h
Labels: enhancement, core

#625 Missing flaxengine api tags
  Source/Engine/Debug/Exception.h
  Source/Engine/Scripting/ManagedCLR/MField.h
  Source/Engine/Utilities/StateMachine.h
Labels: core, fix

#626 Added Vector*::Angle functions to C++
  Source/Engine/Core/Math/Vector2.h
  Source/Engine/Core/Math/Vector3.h
Labels: enhancement, core

#632 fix typos & wording in README.md
  README.md
Labels: documentation, fix
