Repository FlaxEngine/FlaxEngine, pull requests merged in 2021-03, with the labels that each got.

#283 Add Render2D Tint
  Source/Engine/Render2D/Render2D.cpp
  Source/Engine/Render2D/Render2D.h
Labels: enhancement, graphics

#285 some quotes from discord
  Source/Editor/Windows/SplashScreen.cpp
Labels: editor

#287 Use proper remap function instead
  Source/Engine/Visject/VisjectGraph.cpp
Labels: fix

#297 Update .gitignore
  .gitignore
Labels: enhancement, fix

#288 Improve Visual Studio Code solution generation
  Source/Editor/Modules/SourceCodeEditing/InBuildSourceCodeEditor.cs
  Source/Editor/Scripting/CodeEditors/VisualStudioCodeEditor.cpp
  Source/Tools/Flax.Build/Build/Builder.Projects.cs
  Source/Tools/Flax.Build/Projects/VisualStudioCode/VisualStudioCodeProjectGenerator.cs
Labels: enhancement

#304 Element Containers
  Source/Editor/CustomEditors/Elements/Container/CustomElement.cs
  Source/Editor/CustomEditors/Elements/Container/GroupElement.cs
  Source/Editor/CustomEditors/Elements/Container/HorizontalPanelElement.cs
  Source/Editor/CustomEditors/Elements/Container/PropertiesListElement.cs
  Source/Editor/CustomEditors/Elements/Container/SpaceElement.cs
  Source/Editor/CustomEditors/Elements/Container/TreeElement.cs
  Source/Editor/CustomEditors/Elements/Container/TreeNodeElement.cs
  Source/Editor/CustomEditors/Elements/Container/VerticalPanelElement.cs
  Source/Editor/CustomEditors/LayoutElementsContainer.cs
Labels: editor, enhancement

#250 Network sockets improvements.
  Source/Engine/Platform/Base/NetworkBase.cpp
  Source/Engine/Platform/Base/NetworkBase.h
  Source/Engine/Platform/Win32/Win32Network.cpp
  Source/Engine/Platform/Win32/Win32Network.h
Labels: enhancement, platform

#296 Build Issue rissen from moving AssetsContainer
  Source/Engine/Content/Content.Build.cs
Labels: fix, tools

#267 Fix TextBox caret and selection size with custom DPI
  Source/Engine/UI/GUI/Common/RichTextBoxBase.cs
  Source/Engine/UI/GUI/Common/TextBox.cs
Labels: fix, ui

#219 Implement per monitor/window dpi
  Source/Editor/Content/Proxy/ShaderProxy.cs
  Source/Editor/Editor.cs
  Source/Editor/GUI/ContextMenu/ContextMenuBase.cs
  Source/Editor/GUI/Dialogs/Dialog.cs
  Source/Editor/GUI/Docking/DockPanel.cs
  Source/Editor/GUI/MainMenu.cs
  Source/Editor/Modules/WindowsModule.cs
  Source/Editor/Surface/ContextMenu/ContentFinder.cs
  Source/Editor/Utilities/Utils.cs
  Source/Editor/Windows/Assets/MaterialWindow.cs
  Source/Editor/Windows/Assets/ParticleEmitterWindow.cs
  Source/Editor/Windows/ContentWindow.cs
  Source/Engine/Platform/Android/AndroidWindow.cpp
  Source/Engine/Platform/Base/PlatformBase.h
  Source/Engine/Platform/Base/WindowBase.h
  Source/Engine/Platform/Linux/LinuxWindow.cpp
  Source/Engine/Platform/UWP/UWPWindow.h
  Source/Engine/Platform/Window.cs
  Source/Engine/Platform/Windows/WindowsPlatform.cpp
  Source/Engine/Platform/Windows/WindowsWindow.cpp
  Source/Engine/Render2D/FontManager.cpp
  Source/Engine/UI/GUI/Control.cs
  Source/Engine/UI/GUI/RenderOutputControl.cs
  Source/Engine/UI/GUI/Tooltip.cs
  Source/Engine/UI/GUI/WindowRootControl.cs
Labels: core, enhancement, ui

#314 Fix text not getting clipped in Label with negative margins
  Source/Engine/UI/GUI/Common/Label.cs
Labels: fix, ui

#273 Some tiny UI improvements
  Source/Editor/CustomEditors/Dedicated/UIControlEditor.cs
  Source/Editor/GUI/Docking/DockPanel.cs
  Source/Editor/Viewport/EditorViewport.cs
  Source/Editor/Windows/SceneTreeWindow.cs
  Source/Engine/Utilities/StringUtils.cs
Labels: editor, enhancement, ui

#309 Better UI Control editor
  Source/Editor/CustomEditors/Dedicated/UIControlEditor.cs
  Source/Engine/UI/GUI/Control.Bounds.cs
  Source/Engine/UI/GUI/Control.cs
Labels: editor, enhancement, ui

#284 Editor viewport improvements
  Source/Editor/Options/ViewportOptions.cs
  Source/Editor/Viewport/Cameras/FPSCamera.cs
  Source/Editor/Viewport/EditorViewport.cs
  Source/Editor/Windows/EditGameWindow.cs
Labels: editor, enhancement, ui

#302 Declaration sorting of script members
  Source/Editor/Content/Items/VisualScriptItem.cs
  Source/Editor/CustomEditors/Editors/GenericEditor.cs
  Source/Editor/Options/GeneralOptions.cs
  Source/Editor/Scripting/ScriptType.cs
Labels: editor, enhancement

#336 Fix fullscreen dx11/dx12.
  Source/Engine/GraphicsDevice/DirectX/DX11/GPUSwapChainDX11.cpp
  Source/Engine/GraphicsDevice/DirectX/DX12/GPUSwapChainDX12.cpp
Labels: fix, platform

#343 Tweak Camera.ProjectPoint and ScreenToGameViewport
  Source/Engine/Engine/Engine.cpp
  Source/Engine/Engine/Engine.h
  Source/Engine/Engine/Screen.cpp
  Source/Engine/Engine/Screen.h
  Source/Engine/Input/Input.cpp
  Source/Engine/Level/Actors/Camera.cpp
  Source/Engine/Level/Actors/Camera.h
Labels: documentation, enhancement

#355 Separate ContainerControl Self/Children draw code.
  Source/Engine/UI/GUI/Common/Border.cs
  Source/Engine/UI/GUI/Common/Button.cs
  Source/Engine/UI/GUI/Common/Image.cs
  Source/Engine/UI/GUI/Common/ProgressBar.cs
  Source/Engine/UI/GUI/Common/RenderToTextureControl.cs
  Source/Engine/UI/GUI/Common/RichTextBoxBase.cs
  Source/Engine/UI/GUI/Common/TextBox.cs
  Source/Engine/UI/GUI/Common/TextBoxBase.cs
  Source/Engine/UI/GUI/ContainerControl.cs
Labels: enhancement, fix, ui

#366 UICanvas Culling
  Source/Engine/UI/UICanvas.cs
Labels: enhancement, ui

#365 Select Prefabs First
  Source/Editor/Gizmo/TransformGizmo.cs
Labels: editor, enhancement

#388 Matrix3x3.cs documentation fixes
  Source/Engine/Core/Math/Matrix3x3.cs
Labels: documentation

#399 Fix DPI regression: use the overrideable RootWindow instead of _root
  Source/Engine/UI/GUI/Control.cs
Labels: fix, ui

#400 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#412 Add overwrite prompt for SaveDialog.
  Source/Engine/Platform/Windows/WindowsFileSystem.cpp
Labels: enhancement, platform

#413 Scale dockwindow size by DPI scale
  Source/Editor/GUI/Docking/DockWindow.cs
Labels: editor, fix
