Repository FlaxEngine/FlaxEngine, pull requests merged in 2021-01, with the labels that each got.

#86 Adding contributors names to AboutDialog.
  Source/Editor/Windows/AboutDialog.cs
Labels: editor

#87 Fix shortcuts (F5, F6, F11) in play mode
  Source/Editor/Editor.cs
  Source/Editor/Windows/GameWindow.cs
  Source/Editor/Windows/SceneEditorWindow.cs
Labels: editor, enhancement

#48 Add Icon size settings in styles
  Source/Editor/GUI/ToolStrip.cs
  Source/Editor/Windows/ToolboxWindow.cs
  Source/Engine/UI/GUI/Style.cs
Labels: editor, enhancement

#81 GamePlugin only used in PlayMode/Cooked game.
  Source/Editor/States/PlayingState.cs
  Source/Engine/Scripting/Plugins/PluginManager.cs
Labels: core, enhancement

#90 Make constants use the actual const keyword
  Source/Editor/Utilities/Constants.cs
  Source/Tools/Flax.Build/Bindings/BindingsGenerator.Api.cs
Labels: enhancement, tools

#70 Correct DockHintWindow drag offset if it was invalid when initializing
  Source/Editor/GUI/Docking/DockHintWindow.cs
Labels: editor, enhancement

#84 Return focus to the previous control when closing a context menu
  Source/Editor/GUI/ContextMenu/ContextMenuBase.cs
Labels: editor, enhancement

#100 Fix to disable terrain and foliage buttons if no scene is present
  Source/Editor/Tools/Foliage/FoliageTab.cs
  Source/Editor/Tools/Terrain/CarveTab.cs
Labels: bug, editor

#103 Include golden ratio constant
  Source/Engine/Core/Math/Mathf.cs
Labels: core, enhancement

#105 Adding Camera Orientation to editor view menu.
  Source/Editor/Viewport/EditorViewport.cs
Labels: editor, enhancement

#109 Fixing Windows position (on startup) for multi screens.
  Source/Editor/Modules/WindowsModule.cs
Labels: bug, editor

#83 Battery information.
  Source/Engine/Platform/Base/PlatformBase.cpp
  Source/Engine/Platform/Base/PlatformBase.h
  Source/Engine/Platform/BatteryInfo.h
  Source/Engine/Platform/Win32/Win32Platform.cpp
  Source/Engine/Platform/Win32/Win32Platform.h
Labels: enhancement, platform

#93 Fixing open file dialog.
  Source/Engine/Platform/Windows/WindowsFileSystem.cpp
Labels: bug, platform

#113 Fixed Typos and padding for about window
  Source/Editor/Content/Import/ModelImportEntry.cs
  Source/Editor/GUI/Docking/MasterDockPanel.cs
  Source/Editor/History/HistoryStack.cs
  Source/Editor/Scripting/ScriptsBuilder.cpp
  Source/Editor/Windows/AboutDialog.cs
  Source/Editor/Windows/Assets/SceneAnimationWindow.cs
  Source/Editor/Windows/GameWindow.cs
  Source/Engine/Content/Loading/ContentLoadingManager.cpp
  Source/Engine/Core/Log.cpp
  Source/Engine/Core/ObjectsRemovalService.cpp
  Source/Engine/Engine/Engine.cpp
  Source/Engine/GraphicsDevice/DirectX/DX12/GPUContextDX12.cpp
  Source/Engine/GraphicsDevice/DirectX/IncludeDirectXHeaders.h
  Source/Engine/GraphicsDevice/Vulkan/CmdBufferVulkan.cpp
  Source/Engine/GraphicsDevice/Vulkan/GPUContextVulkan.cpp
  Source/Engine/Particles/ParticleManager.cpp
  Source/Engine/Platform/Base/WindowsManager.cpp
  Source/Engine/Render2D/FontAsset.cpp
  Source/Engine/Utilities/RectPack.h
Labels: enhancement

#114 Fix NearEqual (GPU Particle) missing implementation.
  Source/Engine/Visject/ShaderGraph.cpp
Labels: graphics

#118 Add more descriptive error message
  Source/Editor/Cooker/Steps/ValidateStep.cpp
Labels: enhancement

#110 Fix tracking mouse offset on high DPI screens
  Source/Engine/UI/GUI/WindowRootControl.cs
Labels: bug

#119 Spelling fixes.
  Source/Editor/Surface/AnimGraphSurface.cs
  Source/Editor/Surface/Archetypes/Animation.cs
  Source/Engine/Animations/Graph/AnimGroup.Animation.cpp
Labels: enhancement

#107 Visject Node Formatter and improved connection dragging
  Source/Editor/Surface/Archetypes/Packing.cs
  Source/Editor/Surface/Elements/Box.cs
  Source/Editor/Surface/VisjectSurface.ContextMenu.cs
  Source/Editor/Surface/VisjectSurface.Formatting.cs
  Source/Editor/Surface/VisjectSurface.Input.cs
Labels: editor, enhancement

#131 Fix Issue #127: Get Node Transform
  Source/Editor/Surface/Archetypes/Animation.cs
Labels: fix

#138 Added contribution guidelines
  CONTRIBUTING.md
Labels: enhancement

#141 Fix fade distance (use input box as well)
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: fix

#144 Collisions helper enhancement
  Source/Engine/Core/Math/CollisionsHelper.cpp
  Source/Engine/Core/Math/CollisionsHelper.h
Labels: core, enhancement

#147 Fixed the issue when slope limit was set to 90 degrees flax crashed.
  Source/Engine/Physics/Colliders/CharacterController.cpp
Labels: fix

#150 Added Node to Mix Normal Maps
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement

#151 Added rotator node for material editor
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement, graphics

#152 Document the clockwise order of the indices
  Source/Engine/Graphics/Mesh.cs
  Source/Engine/Graphics/Models/Mesh.h
  Source/Engine/Graphics/Models/SkinnedMesh.h
  Source/Engine/Graphics/SkinnedMesh.cs
Labels: documentation

#149 Added option to invert panning direction in editor viewport
  Source/Editor/Options/ViewportOptions.cs
  Source/Editor/Viewport/Cameras/FPSCamera.cs
  Source/Editor/Viewport/Cameras/ViewportCamera.cs
  Source/Editor/Viewport/EditorViewport.cs
Labels: editor, enhancement

#163 Added Sphere Mask node
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement

#161 Added Remap node for all graphs
  Source/Editor/Surface/Archetypes/Math.cs
  Source/Engine/Visject/ShaderGraph.cpp
  Source/Engine/Visject/VisjectGraph.cpp
Labels: enhancement

#143 Improve build times in development configuration
  Source/Tools/Flax.Build/Build/NativeCpp/CompileEnvironment.cs
  Source/Tools/Flax.Build/Build/Target.cs
  Source/Tools/Flax.Build/Platforms/Windows/WindowsToolchainBase.cs
Labels: enhancement

#168 Added UV Tiling & Offset node
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement, graphics

#148 Use more modern file dialog for browsing folders
  Source/Engine/Platform/Windows/WindowsFileSystem.cpp
Labels: enhancement

#160 Low-Level Networking
  Source/Engine/Platform/Base/NetworkBase.cpp
  Source/Engine/Platform/Base/NetworkBase.h
  Source/Engine/Platform/Network.h
  Source/Engine/Platform/Types.h
  Source/Engine/Platform/Win32/Win32Network.cpp
  Source/Engine/Platform/Win32/Win32Network.h
  Source/Engine/Platform/Win32/Win32Platform.cpp
  Source/Engine/Platform/Win32/Win32Platform.h
  Source/Engine/Platform/Windows/WindowsPlatform.cpp
Labels: core, enhancement, platform

#169 Added DDX / DDY nodes
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement, graphics

#172 Disable CTRL+W in game mode
  Source/Editor/Options/InputBinding.cs
  Source/Editor/Windows/GameWindow.cs
Labels: editor, fix

#171 Improve first time setup
  CONTRIBUTING.md
  Development/Scripts/Linux/CallBuildTool.sh
  Development/Scripts/Windows/CallBuildTool.bat
  GenerateProjectFiles.bat
  README.md
Labels: documentation, enhancement

#177 Fix viewport zooming
  Source/Editor/Viewport/Cameras/ViewportCamera.cs
  Source/Editor/Viewport/EditorViewport.cs
  Source/Editor/Viewport/Previews/AssetPreview.cs
  Source/Editor/Viewport/Previews/TexturePreview.cs
  Source/Editor/Windows/Assets/ModelWindow.cs
  Source/Editor/Windows/Assets/SkinnedModelWindow.cs
Labels: editor, fix
