Repository FlaxEngine/FlaxEngine, pull requests merged in 2021-04, with the labels that each got.

#414 Bump up default Update FPS to 60
  Source/Engine/Engine/Time.cpp
Labels: core, enhancement

#425 Add sweep and overlap physics queries for capsule shapes
  Source/Engine/Physics/Physics.Queries.cpp
  Source/Engine/Physics/Physics.h
Labels: enhancement, physics

#417 UI LocalLocation
  Source/Editor/CustomEditors/Dedicated/UIControlEditor.cs
  Source/Engine/UI/GUI/Control.Bounds.cs
Labels: editor, enhancement, ui

#418 UI AchorPresetPopup Shift and Ctrl Modes
  Source/Editor/CustomEditors/Dedicated/UIControlEditor.cs
  Source/Engine/UI/GUI/Control.Bounds.cs
Labels: editor, enhancement, ui

#442 Fix #408 by being more precise in some places
  Source/Engine/Level/Actors/SplineModel.cpp
Labels: fix

#440 Super smooth quaternion editing
  Source/Editor/CustomEditors/Editors/QuaternionEditor.cs
Labels: editor, enhancement

#446 Fix "This" node output type.
  Source/Editor/Surface/Archetypes/Tools.cs
Labels: enhancement

#450 Slightly improve the random byte generation code
  Source/Engine/Utilities/Extensions.cs
Labels: enhancement

#435 Expose Px Set/GetUpDirection.
  Source/Engine/Physics/Colliders/CharacterController.cpp
  Source/Engine/Physics/Colliders/CharacterController.h
Labels: enhancement, physics

#454 Fix 3D audio placement for XAudio2 and OpenAL
  Source/Engine/Audio/OpenAL/AudioBackendOAL.cpp
  Source/Engine/Audio/XAudio2/AudioBackendXAudio2.cpp
Labels: audio, fix

#463 Add initializer list support for arrays
  Source/Engine/Core/Collections/Array.h
Labels: enhancement, scripting

#464 GetChildAt should do it in reverse order to respect z order
  Source/Engine/UI/GUI/ContainerControl.cs
Labels: fix, ui

#469 Fix issue #460
  Source/Engine/UI/GUI/Tooltip.cs
Labels: fix, ui

#470 Fix issue #468
  Source/Engine/UI/GUI/Tooltip.cs
Labels: editor, fix

#474 Protected Internal access modifier fix
  Source/Engine/Scripting/ManagedCLR/MClass.Mono.cpp
  Source/Engine/Scripting/ManagedCLR/MField.Mono.cpp
  Source/Engine/Scripting/ManagedCLR/MMethod.Mono.cpp
  Source/Engine/Scripting/ManagedCLR/MTypes.h
Labels: fix, scripting

#475 [CLEAN] Added missing includes in headers
  Source/Editor/Cooker/CookingData.h
  Source/Engine/Animations/AnimationData.h
  Source/Engine/CSG/HalfEdge.h
  Source/Engine/Content/Loading/ContentLoadTask.h
  Source/Engine/Content/Upgraders/ModelAssetUpgrader.h
  Source/Engine/Content/Upgraders/ShaderAssetUpgrader.h
  Source/Engine/Content/Upgraders/SkinnedModelAssetUpgrader.h
  Source/Engine/Core/Config/LayersTagsSettings.h
  Source/Engine/Graphics/Models/SkeletonData.h
  Source/Engine/Input/InputSettings.h
  Source/Engine/Platform/IGuiData.h
  Source/Engine/Platform/Win32/Win32ConditionVariable.h
  Source/Engine/Scripting/ScriptingCalls.h
Labels: enhancement

#476 Fix textbox bugs
  Source/Engine/UI/GUI/Common/TextBoxBase.cs
Labels: fix, ui

#477 BindingsGenerator, Adding the namespace of a field from another module.
  Source/Tools/Flax.Build/Bindings/BindingsGenerator.CSharp.cs
Labels: enhancement, tools

#411 Added some qutoes
  Source/Editor/Windows/SplashScreen.cpp
Labels: editor, enhancement

#465 Misc math changes
  Source/Engine/Core/Math/Math.h
  Source/Engine/Core/Math/Vector3.h
Labels: enhancement, scripting

#472 Fix missing rotation parameters in capsule physics queries
  Source/Engine/Physics/Physics.Queries.cpp
  Source/Engine/Physics/Physics.h
Labels: enhancement, physics
