Repository FlaxEngine/FlaxEngine, pull requests merged in 2021-02, with the labels that each got.

#179 Set minimum width and height for texture description in motion blur
  Source/Engine/Renderer/MotionBlurPass.cpp
Labels: fix

#184 Fix InputText & Typo.
  Source/Engine/Input/Keyboard.h
Labels: fix

#195 Fix conversion to degrees in Vector3.Angle
  Source/Engine/Core/Math/Vector3.cs
Labels: fix

#185 Add Sign, Any, All and Blackbody shader nodes
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement, graphics

#212 Fixed issue #210: Deleting non-existent folders from the editor.
  Source/Editor/Content/Tree/ContentTreeNode.cs
  Source/Editor/Windows/ContentWindow.cs
Labels: editor, fix

#207 [Editor/Docking] Bring window to front on focus
  Source/Editor/GUI/Docking/DockWindow.cs
Labels: editor, enhancement

#215 Fix issue #214: Debug draw with uneven amount of lines crashes
  Source/Engine/Debug/DebugDraw.cpp
Labels: fix

#216 Added FLAXENGINE_API macro to class JsonAsset.
  Source/Engine/Content/JsonAsset.h
Labels: core, fix

#154 Optimisied Blend Normal Node
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.cpp
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.h
Labels: enhancement

#224 [C++] Added FLAXENGINE_API macro on SettingsBase class
  Source/Engine/Core/Config/LayersTagsSettings.h
  Source/Engine/Core/Config/Settings.h
Labels: core, fix

#236 Fix crash in Windows platform logging with long lines
  Source/Engine/Platform/Windows/WindowsPlatform.cpp
Labels: fix, platform

#227 [EDITOR] Fixed layer matrix order ( issue #153 )
  Source/Editor/CustomEditors/Dedicated/LayersMatrixEditor.cs
Labels: editor, fix

#241 Fix UI - mouse capturing and tree node hovering
  Source/Editor/GUI/Tree/TreeNode.cs
  Source/Engine/Platform/Base/WindowBase.h
  Source/Engine/Platform/Windows/WindowsWindow.cpp
Labels: confirmed, editor, fix

#244 Network tweaks
  Source/Engine/Platform/Base/NetworkBase.cpp
  Source/Engine/Platform/Base/NetworkBase.h
  Source/Engine/Platform/Win32/Win32Network.cpp
  Source/Engine/Platform/Win32/Win32Network.h
Labels: enhancement

#242 Render2D Triangle Functions
  Source/Engine/Render2D/Render2D.cpp
  Source/Engine/Render2D/Render2D.h
Labels: enhancement, graphics

#108 Adding Convert feature to Actor context menu.
  Source/Editor/Modules/SceneEditingModule.cs
  Source/Editor/Windows/SceneTreeWindow.ContextMenu.cs
Labels: editor, enhancement

#111 Added and refactored several extension methods for Random
  Source/Engine/Utilities/Extensions.cs
Labels: core, enhancement

#246 Tooltip background.
  Source/Engine/UI/GUI/Tooltip.cs
Labels: editor, fix, ui

#256 Add RGB & HSV Conversion nodes
  Source/Editor/Surface/Archetypes/Material.cs
  Source/Engine/Tools/MaterialGenerator/MaterialGenerator.Material.cpp
Labels: enhancement

#258 Fix building engine with latest Windows platform toolset only
  Source/Tools/Flax.Build/Platforms/UWP/UWPPlatform.cs
  Source/Tools/Flax.Build/Platforms/UWP/UWPToolchain.cs
  Source/Tools/Flax.Build/Platforms/Windows/WindowsPlatform.cs
Labels: enhancement

#253 Add virtual memory allocation utilities
  Source/Engine/Platform/Base/PlatformBase.h
  Source/Engine/Platform/Unix/UnixPlatform.cpp
  Source/Engine/Platform/Unix/UnixPlatform.h
  Source/Engine/Platform/Win32/Win32Platform.cpp
  Source/Engine/Platform/Win32/Win32Platform.h
Labels: enhancement, platform

#268 Add Dockwindow icons
  Source/Editor/GUI/Docking/DockPanelProxy.cs
  Source/Editor/GUI/Docking/DockWindow.cs
  Source/Editor/Windows/ContentWindow.cs
  Source/Editor/Windows/DebugLogWindow.cs
Labels: editor, enhancement, ui

#271 [C++] Added auto serialization by default in C++ script template
  Content/Editor/Scripting/ScriptTemplate.h
Labels: editor, enhancement

#254 Add some defaults to Quaternion helpers
  Source/Engine/Core/Math/Quaternion.cs
Labels: enhancement

#257 Add Vector3 Clamp
  Source/Engine/Core/Math/Vector2.cs
  Source/Engine/Core/Math/Vector3.cs
  Source/Engine/Core/Math/Vector4.cs
Labels: core, enhancement

#279 Reroute Nodes and Arrow Key Navigation
  Source/Editor/Surface/Archetypes/Tools.cs
  Source/Editor/Surface/ContextMenu/VisjectCMItem.cs
  Source/Editor/Surface/Elements/OutputBox.cs
  Source/Editor/Surface/SurfaceNode.cs
  Source/Editor/Surface/Undo/BoxHandle.cs
  Source/Editor/Surface/Undo/ConnectBoxesAction.cs
  Source/Editor/Surface/VisjectSurface.CopyPaste.cs
  Source/Editor/Surface/VisjectSurface.Draw.cs
  Source/Editor/Surface/VisjectSurface.Input.cs
  Source/Editor/Surface/VisjectSurface.cs
  Source/Engine/Engine/Time.h
  Source/Engine/Visject/ShaderGraph.cpp
  Source/Engine/Visject/VisjectGraph.cpp
Labels: editor, enhancement, tools

#282 Tweak camera orientation.
  Source/Editor/Viewport/EditorViewport.cs
Labels: editor, enhancement
